import type { ServiceVisit, Vehicle } from "./types";

// Seed garage shown to first-time visitors so the demo never opens empty.
// The July 2026 Pep Boys visit is transcribed from a real invoice; the rest
// are realistic composites across different shops to show the cross-shop story.

export const seedVehicles: Vehicle[] = [
  {
    id: "veh-mazda3",
    year: 2016,
    make: "Mazda",
    model: "3",
    vin: "JM1BM1T7XG1284334",
    licensePlate: "WA BMG4770",
    nickname: null,
    currentMileage: 62786,
    mileageAsOf: "2026-07-15",
  },
  {
    id: "veh-outback",
    year: 2019,
    make: "Subaru",
    model: "Outback",
    vin: null,
    licensePlate: "WA CKR2215",
    nickname: "Nat's Outback",
    currentMileage: 48102,
    mileageAsOf: "2026-03-21",
  },
];

export const seedVisits: ServiceVisit[] = [
  {
    id: "vis-pepboys-2026-07",
    vehicleId: "veh-mazda3",
    source: "seed",
    receiptThumbnail: null,
    shop: {
      name: "Pep Boys",
      storeNumber: "6449",
      address: "5601 15th Ave NW, Seattle, WA 98107",
      phone: "(206) 783-4423",
    },
    workOrderNumber: "2068633",
    dateIn: "2026-07-07",
    dateOut: "2026-07-15",
    mileage: 62786,
    serviceManager: "Jonathon Kindle",
    technicians: ["Jeffrey K"],
    lineItems: [
      { description: "Pennzoil Platinum synthetic oil change", kind: "labor", quantity: 1, unitPrice: 39.04, total: 39.04, performedBy: "Jeffrey K" },
      { description: "0W-20 Platinum full synthetic oil (bulk)", kind: "part", quantity: 4, unitPrice: 13.99, total: 55.96, performedBy: null },
      { description: "Oil filter", kind: "part", quantity: 1, unitPrice: 9.99, total: 9.99, performedBy: null },
      { description: "Tire rotation", kind: "labor", quantity: 1, unitPrice: 9.99, total: 9.99, performedBy: "Jeffrey K" },
      { description: "Reset maintenance required display", kind: "labor", quantity: 1, unitPrice: 9.99, total: 9.99, performedBy: "Jeffrey K" },
      { description: "Brake system inspection", kind: "labor", quantity: 1, unitPrice: 0, total: 0, performedBy: "Jeffrey K" },
      { description: "Complimentary vehicle inspection", kind: "labor", quantity: 1, unitPrice: 0, total: 0, performedBy: "Jeffrey K" },
      { description: "Shop fee", kind: "fee", quantity: 1, unitPrice: 6.59, total: 6.59, performedBy: null },
    ],
    totals: { parts: 65.95, labor: 59.02, fees: 6.59, tax: 13.88, total: 145.44, paymentMethod: "Visa •••• 3911" },
    diagnostics: {
      brakeLinings: [
        { position: "front-left", value: 8, unit: "32nds" },
        { position: "front-right", value: 8, unit: "32nds" },
        { position: "rear-left", value: 6, unit: "32nds" },
        { position: "rear-right", value: 6, unit: "32nds" },
      ],
      rotorThickness: [],
      tireTreadDepths: [
        { position: "front-left", value: 6, unit: "32nds" },
        { position: "front-right", value: 6, unit: "32nds" },
        { position: "rear-left", value: 6, unit: "32nds" },
        { position: "rear-right", value: 5, unit: "32nds" },
      ],
      notes: "Customer reports squeaking during braking. Battery test requested.",
    },
    warranties: [
      {
        description: "Installed parts replaced free if they fail within 6 months or 6,000 miles",
        coverageType: "parts",
        months: 6,
        miles: 6000,
        appliesTo: "Installed parts (excludes filters and fluids)",
      },
      {
        description: "Service and parts not covered by other warranties: 90 days or 3,000 miles",
        coverageType: "parts_and_labor",
        months: 3,
        miles: 3000,
        appliesTo: "Oil change service, tire rotation",
      },
    ],
  },
  {
    id: "vis-goodyear-2025-11",
    vehicleId: "veh-mazda3",
    source: "seed",
    receiptThumbnail: null,
    shop: {
      name: "Goodyear Auto Service",
      storeNumber: "4187",
      address: "1517 NW Market St, Seattle, WA 98107",
      phone: "(206) 782-2710",
    },
    workOrderNumber: "GY-118276",
    dateIn: "2025-11-14",
    dateOut: "2025-11-14",
    mileage: 57412,
    serviceManager: "Dana Whitfield",
    technicians: ["Marcus D"],
    lineItems: [
      { description: "Front brake pads, ceramic", kind: "part", quantity: 1, unitPrice: 89.99, total: 89.99, performedBy: null },
      { description: "Front rotors, resurfaced", kind: "labor", quantity: 2, unitPrice: 45.0, total: 90.0, performedBy: "Marcus D" },
      { description: "Brake service labor", kind: "labor", quantity: 1.8, unitPrice: 129.0, total: 232.2, performedBy: "Marcus D" },
    ],
    totals: { parts: 89.99, labor: 322.2, fees: 0, tax: 41.94, total: 454.13, paymentMethod: "Visa •••• 3911" },
    diagnostics: null,
    warranties: [
      {
        description: "Brake pads warranted against wear-out for 24 months or 24,000 miles",
        coverageType: "parts",
        months: 24,
        miles: 24000,
        appliesTo: "Front brake pads",
      },
      {
        description: "Brake service labor covered for 12 months or 12,000 miles",
        coverageType: "labor",
        months: 12,
        miles: 12000,
        appliesTo: "Front brake service labor",
      },
    ],
  },
  {
    id: "vis-mazda-dealer-2024-08",
    vehicleId: "veh-mazda3",
    source: "seed",
    receiptThumbnail: null,
    shop: {
      name: "University Mazda",
      storeNumber: null,
      address: "4544 Roosevelt Way NE, Seattle, WA 98105",
      phone: "(206) 634-3070",
    },
    workOrderNumber: "RO-448291",
    dateIn: "2024-08-22",
    dateOut: "2024-08-22",
    mileage: 45210,
    serviceManager: null,
    technicians: ["S. Okafor"],
    lineItems: [
      { description: "45,000 mile scheduled maintenance", kind: "labor", quantity: 1, unitPrice: 289.0, total: 289.0, performedBy: "S. Okafor" },
      { description: "Cabin air filter", kind: "part", quantity: 1, unitPrice: 34.5, total: 34.5, performedBy: null },
      { description: "Brake fluid exchange", kind: "labor", quantity: 1, unitPrice: 119.0, total: 119.0, performedBy: "S. Okafor" },
    ],
    totals: { parts: 34.5, labor: 408.0, fees: 12.5, tax: 46.28, total: 501.28, paymentMethod: "Amex •••• 1005" },
    diagnostics: null,
    warranties: [
      {
        description: "Genuine Mazda parts and dealer labor: 12 months or 12,000 miles",
        coverageType: "parts_and_labor",
        months: 12,
        miles: 12000,
        appliesTo: "Scheduled maintenance items",
      },
    ],
  },
  {
    id: "vis-discount-tire-2023-10",
    vehicleId: "veh-mazda3",
    source: "seed",
    receiptThumbnail: null,
    shop: {
      name: "Discount Tire",
      storeNumber: "WAS 21",
      address: "12233 Aurora Ave N, Seattle, WA 98133",
      phone: "(206) 364-1955",
    },
    workOrderNumber: "1187364",
    dateIn: "2023-10-06",
    dateOut: "2023-10-06",
    mileage: 33890,
    serviceManager: null,
    technicians: [],
    lineItems: [
      { description: "Michelin Defender T+H 205/60R16", kind: "part", quantity: 4, unitPrice: 142.0, total: 568.0, performedBy: null },
      { description: "Installation, balancing, TPMS service", kind: "labor", quantity: 4, unitPrice: 22.0, total: 88.0, performedBy: null },
      { description: "State tire fee", kind: "fee", quantity: 4, unitPrice: 1.0, total: 4.0, performedBy: null },
    ],
    totals: { parts: 568.0, labor: 88.0, fees: 4.0, tax: 67.32, total: 727.32, paymentMethod: "Visa •••• 3911" },
    diagnostics: null,
    warranties: [
      {
        description: "Tread wear-out warranty, 80,000 miles from install",
        coverageType: "parts",
        months: null,
        miles: 80000,
        appliesTo: "Michelin Defender tires (4)",
      },
    ],
  },
  {
    id: "vis-subaru-dealer-2026-03",
    vehicleId: "veh-outback",
    source: "seed",
    receiptThumbnail: null,
    shop: {
      name: "Carter Subaru Ballard",
      storeNumber: null,
      address: "5201 Leary Ave NW, Seattle, WA 98107",
      phone: "(206) 782-7475",
    },
    workOrderNumber: "RO-90417",
    dateIn: "2026-03-21",
    dateOut: "2026-03-21",
    mileage: 48102,
    serviceManager: null,
    technicians: ["T. Nguyen"],
    lineItems: [
      { description: "Full synthetic oil change", kind: "labor", quantity: 1, unitPrice: 89.95, total: 89.95, performedBy: "T. Nguyen" },
      { description: "Engine air filter", kind: "part", quantity: 1, unitPrice: 42.0, total: 42.0, performedBy: null },
      { description: "Multi-point inspection", kind: "labor", quantity: 1, unitPrice: 0, total: 0, performedBy: "T. Nguyen" },
    ],
    totals: { parts: 42.0, labor: 89.95, fees: 8.0, tax: 14.42, total: 154.37, paymentMethod: "Visa •••• 8834" },
    diagnostics: {
      brakeLinings: [
        { position: "front-left", value: 7, unit: "32nds" },
        { position: "front-right", value: 7, unit: "32nds" },
        { position: "rear-left", value: 5, unit: "32nds" },
        { position: "rear-right", value: 5, unit: "32nds" },
      ],
      rotorThickness: [],
      tireTreadDepths: [
        { position: "front-left", value: 7, unit: "32nds" },
        { position: "front-right", value: 7, unit: "32nds" },
        { position: "rear-left", value: 6, unit: "32nds" },
        { position: "rear-right", value: 6, unit: "32nds" },
      ],
      notes: null,
    },
    warranties: [
      {
        description: "Dealer parts and labor: 12 months or 12,000 miles",
        coverageType: "parts_and_labor",
        months: 12,
        miles: 12000,
        appliesTo: "Oil change service, engine air filter",
      },
    ],
  },
  {
    id: "vis-les-schwab-2025-10",
    vehicleId: "veh-outback",
    source: "seed",
    receiptThumbnail: null,
    shop: {
      name: "Les Schwab Tire Center",
      storeNumber: null,
      address: "8500 15th Ave NW, Seattle, WA 98117",
      phone: "(206) 789-1102",
    },
    workOrderNumber: "LS-337120",
    dateIn: "2025-10-11",
    dateOut: "2025-10-11",
    mileage: 44870,
    serviceManager: null,
    technicians: [],
    lineItems: [
      { description: "Tire rotation and balance", kind: "labor", quantity: 1, unitPrice: 0, total: 0, performedBy: null },
      { description: "Flat repair, rear-left", kind: "labor", quantity: 1, unitPrice: 0, total: 0, performedBy: null },
    ],
    totals: { parts: 0, labor: 0, fees: 0, tax: 0, total: 0, paymentMethod: null },
    diagnostics: null,
    warranties: [],
  },
];
